package libw: json;

world json {
    import types;
    export to-string: func(value: json, config: formatter);
}

interface types {
variant json {
    null,
    boolean(bool),
    number(f32),
    str(string),
    array(json-array),
    object(json-object),
}
record json-array {
    items: list<json>
}
record json-object {
    items: list<json-pair>
}
record json-pair {
    key: string,
    value: json,
}

record formatter {
    indent: string,
}
}
