packages:
  - "."
  - "projects/application/*"
  - "projects/frontend/*"
  - "projects/frontend/adapters/*"
  - "projects/backend/*"
  - "projects/backend/adapters/*"
  - "projects/host/*"
  - "projects/platform/*"
  - "projects/platform/desktop/*/*"
  - "projects/platform/mobile/*/*"
  - "projects/communication/*"
  - "projects/tooling/*"
  - "projects/examples/*"
  - "projects/examples/*/*"
  - "projects/examples/*/*/*"

catalog:
  typescript: "^5.9.2"
  vite: "^7.1.5"
  vitest: "^3.2.4"
