//! DSL 解析模块
//! 
//! 提供对 .wae 文件的解析功能，将 DSL 定义转换为数据库 schema。

use std::fs;
use std::path::Path;
use wae_database::{ColumnType, TableSchema};

/// 从 .wae 文件加载并解析 TableSchema
pub fn load_schemas_from_wae_file(path: impl AsRef<Path>) -> Result<Vec<TableSchema>, Box<dyn std::error::Error>> {
    let content = fs::read_to_string(path)?;
    load_schemas_from_wae(&content)
}

/// 从 .wae 字符串加载并解析 TableSchema
pub fn load_schemas_from_wae(wae_str: &str) -> Result<Vec<TableSchema>, Box<dyn std::error::Error>> {
    // 暂时返回空结果，后续将实现完整的解析逻辑
    // 这里需要使用 oak-rbq 解析器来解析 WAE 文件
    let mut schemas = Vec::new();
    
    Ok(schemas)
}

/// 将 TableSchema 转换为 Rust 结构体定义
pub fn generate_rust_schema(schemas: &[TableSchema]) -> String {
    let mut rust_code = String::new();
    
    rust_code.push_str("// Auto-generated by WAE DSL\n\n");
    rust_code.push_str("use wae_database::{TableSchema, ColumnDef, ColumnType};
\n");
    
    for schema in schemas {
        rust_code.push_str(&format!("/// Table schema for {}\n", schema.name));
        rust_code.push_str(&format!("pub fn {}_schema() -> TableSchema {{
", schema.name));
        rust_code.push_str(&format!("    TableSchema::new(\"{}\")\n", schema.name));
        
        for column in &schema.columns {
            rust_code.push_str(&format!("        .column(ColumnDef::new(\"{}\", ColumnType::{})
", column.name, column_type_to_rust_enum(&column.col_type)));
            
            if column.primary_key {
                rust_code.push_str("            .primary_key()
");
            }
            if column.unique {
                rust_code.push_str("            .unique()
");
            }
            if !column.nullable {
                rust_code.push_str("            .not_null()
");
            }
            if let Some(default) = &column.default_value {
                rust_code.push_str(&format!("            .default(\"{:?}\")
", default));
            }
        }
        
        rust_code.push_str("}\n\n");
    }
    
    rust_code
}

/// 将 ColumnType 转换为 Rust 枚举
fn column_type_to_rust_enum(col_type: &ColumnType) -> &'static str {
    match col_type {
        ColumnType::Text => "Text",
        ColumnType::Integer => "Integer",
        ColumnType::Real => "Real",
        ColumnType::Blob => "Blob",
    }
}