//! DSL 解析模块
//! 
//! 提供对 .wae 文件的解析功能，将 DSL 定义转换为数据库 schema。

use std::fs;
use std::path::Path;
use oak_rbq::parser::RbqParser;
use oak_rbq::ast::RbqRoot;
use wae_database::{ColumnDef, ColumnType, DatabaseSchema, TableSchema, IndexDef, ForeignKeyDef, ReferentialAction};

/// 从 .wae 文件加载并解析 TableSchema
pub fn load_schemas_from_wae_file(path: impl AsRef<Path>) -> Result<Vec<TableSchema>, Box<dyn std::error::Error>> {
    let content = fs::read_to_string(path)?;
    load_schemas_from_wae(&content)
}

/// 从 .wae 字符串加载并解析 TableSchema
pub fn load_schemas_from_wae(wae_str: &str) -> Result<Vec<TableSchema>, Box<dyn std::error::Error>> {
    let parser = RbqParser::new();
    let root = parser.parse(wae_str)?;
    
    let mut schemas = Vec::new();
    for item in &root.items {
        if let Some(schema) = parse_rbq_item(item) {
            schemas.push(schema);
        }
    }
    
    Ok(schemas)
}

/// 解析 RBQ 项目为 TableSchema
fn parse_rbq_item(item: &oak_rbq::ast::RbqItem) -> Option<TableSchema> {
    match item {
        oak_rbq::ast::RbqItem::Struct(rbq_struct) => {
            let mut schema = TableSchema::new(&rbq_struct.name);
            
            for field in &rbq_struct.fields {
                let column_type = convert_rbq_type_to_column_type(&field.type_ref);
                let mut column = ColumnDef::new(&field.name, column_type);
                
                // 处理字段属性
                for annotation in &field.annotations {
                    match annotation.name.as_str() {
                        "primary_key" => column = column.primary_key(),
                        "unique" => column = column.unique(),
                        "not_null" => column = column.not_null(),
                        _ => {}
                    }
                }
                
                // 处理默认值
                if let Some(default_value) = &field.default_value {
                    column = column.default(default_value.to_string());
                }
                
                schema = schema.column(column);
            }
            
            Some(schema)
        }
        _ => None,
    }
}

/// 将 RBQ 类型转换为 ColumnType
fn convert_rbq_type_to_column_type(rbq_type: &oak_rbq::ast::RbqType) -> ColumnType {
    match rbq_type {
        oak_rbq::ast::RbqType::Named { path, .. } => {
            match path.as_str() {
                "i32" | "i64" | "int" | "integer" => ColumnType::Integer,
                "f32" | "f64" | "float" | "real" => ColumnType::Real,
                "string" | "text" | "varchar" => ColumnType::Text,
                "bytes" | "blob" => ColumnType::Blob,
                _ => ColumnType::Text,
            }
        }
        _ => ColumnType::Text,
    }
}

/// 将 TableSchema 转换为 Rust 结构体定义
pub fn generate_rust_schema(schemas: &[TableSchema]) -> String {
    let mut rust_code = String::new();
    
    rust_code.push_str("// Auto-generated by WAE DSL\n\n");
    rust_code.push_str("use wae_database::{TableSchema, ColumnDef, ColumnType};
\n");
    
    for schema in schemas {
        rust_code.push_str(&format!("/// Table schema for {}\n", schema.name));
        rust_code.push_str(&format!("pub fn {}_schema() -> TableSchema {{
", schema.name));
        rust_code.push_str(&format!("    TableSchema::new(\"{}\")\n", schema.name));
        
        for column in &schema.columns {
            rust_code.push_str(&format!("        .column(ColumnDef::new(\"{}\", ColumnType::{})
", column.name, column_type_to_rust_enum(&column.r#type)));
            
            if column.primary_key {
                rust_code.push_str("            .primary_key()
");
            }
            if column.unique {
                rust_code.push_str("            .unique()
");
            }
            if column.not_null {
                rust_code.push_str("            .not_null()
");
            }
            if let Some(default) = &column.default {
                rust_code.push_str(&format!("            .default(\"{}\")
", default));
            }
        }
        
        rust_code.push_str("}\n\n");
    }
    
    rust_code
}

/// 将 ColumnType 转换为 Rust 枚举
fn column_type_to_rust_enum(col_type: &ColumnType) -> &'static str {
    match col_type {
        ColumnType::Text => "Text",
        ColumnType::Integer => "Integer",
        ColumnType::Real => "Real",
        ColumnType::Blob => "Blob",
    }
}